name: flask_pipelin

on:
    push:
        branches:
            - main

jobs:
    python_app:
        runs-on: ubuntu_latest
        steps:
            - uses: actions/checkout@v4

            - name: Setting up python in your runner
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: installing dependencies
              run: |
                python.exe -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Setting up test cases
              run: echo "Testing has been complet1ed."
